import sys
print(sys.version)
s=set('hello')
print(s)
s=set(['alex','alex','hello'])
print(s)
s={1,2,3,4,5,6}
s.add('s')
print(s)
s.add(3)
print(s)
s.remove(2)
s.discard(2)##删除元素不会报错
print(s)
p_s={'12','13','14'}
l_s={'121','131','15'}
d_s={'11','12'}
print(p_s&l_s&d_s)#交集
print(p_s|l_s|d_s)#并集
print('差集',l_s-p_s)#被减数减去公共部分
print(p_s^l_s)#交叉补集
s1={1,2}
s2={1,2,3}
s1.update(s2)#更新多个值
print(s1)
d=frozenset('hello')#tuple版的set
print(d)
list1=['alex','alex','yqy']
list1=list(set(list1))#去重(不考虑顺序)
print(list1)